def initial_restaurants():
    return [
        ("Cravings", "Chinese", 1),
        ("The Bread Company", "Sandwiches", 2),
        ("GG BOWL", "Hot Pot", 2),
        ("SGD DUBU SO GONG DONG TOFU & KOREAN BBQ", "Korean", 2), 
        ("Yogi", "Korean", 2),
        ("Mid Summer Lounge", "Chinese", 2),
        ("Cao's Hot Pot", "Chinese,Hot Pot", 3),
        ("Kung Fu BBQ", "Chinese,Hot Pot", 3), 
        ("bb.q Chicken", "Korean,Chicken", 2),
        ("Kajiken", "Ramen,Japanese", 2),
        ("Mala Parlor Hot Pot", "Hot Pot", 3),
        ("Spoon House", "Korean", 2),
        ("J6 Kitchen", "Korean", 1), 
        ("Royal BBQ", "Chinese", 2),
        ("Murphy's Pub", "American", 1),
        ("Szechuan Taste", "Chinese", 2),
        ("EVO", "Chinese", 1),
        ("YGF Malatang", "Hot Pot", 2),
        ("Sticky Rice", "Thai", 2),
        ("C-U La La Noodle", "Chinese", 2),
        ("Shiquan Wonton", "Chinese", 2),
        ("Bangkok Thai", "Thai", 2),
        ("Basil Thai at Urbana", "Thai", 2),
        ("Mia Za's", "Pizza,Italian", 1),
        ("Potbelly", "Sandwiches", 2),
        ("Susuru Ramen Bar", "Ramen,Japanese", 2),
        ("MOVOC China Malatang", "Hot Pot", 2),
        ("POKE LAB", "Poke", 2),
        ("Pho Noodle Station", "Pho", 2),
        ("Cracked the Egg Came First", "Breakfast", 2),
        ("QDOBA Mexican Eats", "Fast Food,Mexican", 1),
        ("Oozu Ramen", "Ramen,Japanese", 2),
        ("Shawarma Joint", "Mediterranean", 2),
        ("Thai Fusion", "Thai", 2),
        ("Ten Second Rice Noodle", "Chinese", 2),
        ("Chipotle", "Mexican,Fast Food", 1),
        ("Legends", "American", 1),
        ("Taco Bell", "Fast Food,Mexican", 1),
        ("The Empanadas House", "Latin American", 1),
        ("Jurassic Grill", "American", 1),
        ("Chopstix", "Chinese", 2),
        ("McDonald's", "Fast Food", 1),
        ("Noodles & Company", "Fast Food", 2),
        ("Burrito King Mexican Grill", "Mexican", 2),
        ("Panda Express", "Chinese,Fast Food", 1),
        ("Jip Bap", "Korean", 2),
        ("Signature Grill", "Indian", 2),
        ("Raising Cane's Chicken Fingers", "Fast Food,Chicken", 2),
        ("Subway", "Sandwiches,Fast Food", 1),
        ("Fat Sandwich Company", "Sandwiches", 1),

        # Off Campus
        ("Watson's Shack & Rail", "American,Chicken", 2),
        ("Neil St. Blues", "American", 2),
        ("Baldarotta's Porketta & Sicilian Sausage", "Italian,Sandwiches", 2),
        ("The Literary", "Coffee, Brunch", 2),
        ("Tres Nopales", "Mexican", 2),
        ("Pizzeria Antica", "Pizza", 2),
        ("Mo's Burritos", "Mexican", 2),
        ("La Bahia Grill", "Mexican", 1),
        ("Fiesta Cafe", "Mexican", 1),
        ("Big Grove Tavern", "American", 2), 
        ("Niro's Gyros", "Greek", 2),
        ("Masijta Grill Korean BBQ", "Korean,Barbecue", 3),
        ("Siam Terrace", "Thai", 2),
        ("Portillo's Champaign", "American", 1),
        ("Oishi Hibachi Steakhouse", "Steakhouse", 3),
        ("Texas Roadhouse", "Steakhouse", 3),
        ("Wingstop", "Chicken", 2),
        ("Olive Garden", "Italian", 2),
        ("The Space", "American", 2),
        ("Naf Naf Grill", "Mediterranean", 1),
        ("Himalayan Chimney", "Indian", 2), 
        ("Kohinoor", "Indian", 2),
        ("Farren's Pub & Eatery", "American", 2),
        ("Red Lobster", "Seafood", 2),
        ("Merry Ann's Diner", "Diner", 1),
        ("Big J J Fish & Chicken", "Chicken", 1),
        ("Chili's", "American", 2),
        ("Lao Sze Chuan", "Chinese", 2),
        ("Yatai", "Japanese", 2),
        ("Black Dog Smoke & Ale House", "Barbecue", 2),
        ("Tenkyu", "Japanese", 2) ]